import type { Organizer, TradingEvent } from './types';

/**
 * The demo catalogue.
 *
 * There is no events backend yet, so this stands in for one. Two decisions worth
 * stating, because a seed file quietly becomes the spec:
 *
 * Dates are relative to a supplied "now" rather than written down. A fixture with
 * hard dates is correct on the day it is written and wrong forever after — the
 * discovery page would fill with events that already happened, which is exactly
 * the state the page is meant to help people avoid.
 *
 * Organizers and speakers are invented. The venues and cities are real, because
 * a map with fictional streets is harder to read, not safer.
 */

const DAY = 24 * 60 * 60 * 1000;
const HOUR = 60 * 60 * 1000;

export const SEED_ORGANIZERS: Organizer[] = [
  {
    id: 'org_tradingnew',
    slug: 'tradingnew',
    name: 'TradingNew',
    initials: 'TN',
    type: 'tradingnew',
    verificationStatus: 'verified',
    description: 'Market education from the team that builds the platform.',
    website: 'https://tradingnew.space',
    country: 'Cyprus',
    followerCount: 48210,
    createdAt: '2022-01-10T00:00:00.000Z',
  },
  {
    id: 'org_keller',
    slug: 'anna-keller',
    name: 'Anna Keller',
    initials: 'AK',
    type: 'individual',
    verificationStatus: 'verified',
    description:
      'Independent financial adviser, CFA. Practical portfolio workshops for private investors, CySEC-regulated.',
    website: 'https://annakeller.example',
    country: 'Cyprus',
    followerCount: 1240,
    createdAt: '2023-03-02T00:00:00.000Z',
  },
  {
    id: 'org_cyprus_club',
    slug: 'cyprus-investors-club',
    name: 'Cyprus Investors Club',
    initials: 'CI',
    type: 'community',
    verificationStatus: 'unverified',
    description:
      'A volunteer-run community of private investors in Cyprus. Monthly meetups since 2022: markets talk, guest speakers, zero sales pitches.',
    website: 'https://cyprusinvestors.example',
    country: 'Cyprus',
    followerCount: 318,
    createdAt: '2022-05-18T00:00:00.000Z',
  },
  {
    id: 'org_lindqvist',
    slug: 'sofia-lindqvist',
    name: 'Sofia Lindqvist',
    initials: 'SL',
    type: 'individual',
    verificationStatus: 'verified',
    description: 'Wealth planning for private investors — estate, tax and long-horizon structure.',
    website: null,
    country: 'Cyprus',
    followerCount: 890,
    createdAt: '2023-09-11T00:00:00.000Z',
  },
  {
    id: 'org_derivatives_circle',
    slug: 'derivatives-study-circle',
    name: 'Derivatives Study Circle',
    initials: 'DS',
    type: 'community',
    verificationStatus: 'unverified',
    description: 'A weekly online reading group working through options fundamentals together.',
    website: null,
    country: null,
    followerCount: 176,
    createdAt: '2024-02-04T00:00:00.000Z',
  },
  {
    id: 'org_macro_institute',
    slug: 'thames-macro-institute',
    name: 'Thames Macro Institute',
    initials: 'TM',
    type: 'institution',
    verificationStatus: 'verified',
    description: 'Independent macroeconomic research and public lectures, London.',
    website: 'https://thamesmacro.example',
    country: 'United Kingdom',
    followerCount: 5420,
    createdAt: '2021-11-30T00:00:00.000Z',
  },
  {
    id: 'org_berlin_fintech',
    slug: 'berlin-fintech-collective',
    name: 'Berlin Fintech Collective',
    initials: 'BF',
    type: 'company',
    verificationStatus: 'verified',
    description: 'Builders and analysts working on payments, banking infrastructure and open finance.',
    website: 'https://berlinfintech.example',
    country: 'Germany',
    followerCount: 2310,
    createdAt: '2023-06-21T00:00:00.000Z',
  },
  {
    id: 'org_tokyo_etf',
    slug: 'tokyo-etf-forum',
    name: 'Tokyo ETF Forum',
    initials: 'TE',
    type: 'institution',
    verificationStatus: 'verified',
    description: 'Index and ETF education for Japanese retail investors.',
    website: 'https://tokyoetf.example',
    country: 'Japan',
    followerCount: 3980,
    createdAt: '2022-08-08T00:00:00.000Z',
  },
  {
    id: 'org_mumbai_money',
    slug: 'mumbai-money-circle',
    name: 'Mumbai Money Circle',
    initials: 'MM',
    type: 'community',
    verificationStatus: 'unverified',
    description: 'Personal finance meetups for salaried professionals in Mumbai.',
    website: null,
    country: 'India',
    followerCount: 640,
    createdAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'org_hudson_risk',
    slug: 'hudson-risk-partners',
    name: 'Hudson Risk Partners',
    initials: 'HR',
    type: 'company',
    verificationStatus: 'verified',
    description: 'Portfolio risk consulting for family offices and independent advisers.',
    website: 'https://hudsonrisk.example',
    country: 'United States',
    followerCount: 1480,
    createdAt: '2022-04-19T00:00:00.000Z',
  },
  {
    id: 'org_cfs_events',
    slug: 'cfs-events',
    name: 'CFS Events Ltd',
    initials: 'CF',
    type: 'company',
    verificationStatus: 'unverified',
    description: 'Conference organizer, Nicosia.',
    website: 'https://cyprusfintechsummit.example',
    country: 'Cyprus',
    followerCount: 210,
    createdAt: '2023-02-27T00:00:00.000Z',
  },
];

type SeedInput = Omit<TradingEvent, 'startsAt' | 'endsAt' | 'createdAt' | 'updatedAt' | 'publishedAt'> & {
  /** Days from "now"; negative for events in the past. */
  inDays: number;
  startHour: number;
  durationHours: number;
};

const BASE: Pick<
  TradingEvent,
  | 'visibility'
  | 'markets'
  | 'tags'
  | 'isFeatured'
  | 'isPromoted'
  | 'createdBy'
  | 'moderationReason'
  | 'cancellationReason'
  | 'coverImageUrl'
  | 'latitude'
  | 'longitude'
  | 'onlineMeetingUrl'
  | 'registrationDeadline'
  | 'importantNotice'
> = {
  visibility: 'public',
  markets: [],
  tags: [],
  isFeatured: false,
  isPromoted: false,
  createdBy: null,
  moderationReason: null,
  cancellationReason: null,
  coverImageUrl: null,
  latitude: null,
  longitude: null,
  onlineMeetingUrl: null,
  registrationDeadline: null,
  importantNotice:
    'Sessions are educational and never contain investment recommendations. Recording availability depends on the organizer.',
};

const DEFAULT_OUTCOMES = [
  'How this topic applies to real portfolios',
  'Common beginner mistakes and how to avoid them',
  'Which TradingNew tools support this workflow',
];

const DEFAULT_AUDIENCE =
  'Beginners and intermediate investors who want practical, hype-free knowledge. No prior experience required unless stated.';

function agenda(items: Array<[string, string, string | null, string]>) {
  return items.map(([time, title, speaker, kind], index) => ({
    id: `ag_${index}`,
    time,
    title,
    speaker,
    kind,
    position: index,
  }));
}

function speakers(items: Array<[string, string, string, string | null]>) {
  return items.map(([initials, name, role, company], index) => ({
    id: `sp_${index}`,
    initials,
    name,
    role,
    company,
    avatarUrl: null,
    position: index,
  }));
}

const SEEDS: SeedInput[] = [
  {
    ...BASE,
    id: 'evt_market_cycles',
    slug: 'understanding-market-cycles',
    title: 'Understanding Market Cycles',
    shortDescription: 'How economic regimes shape returns across asset classes.',
    description:
      'A practical introduction to market cycles: expansion, peak, contraction and recovery — and how each regime historically treated stocks, bonds, cash and gold.\n\nBuilt on the same labelled data you see across TradingNew, so every chart in the session is one you can open yourself afterwards.',
    coverGradient: 'linear-gradient(135deg,#0a1c33,#081018)',
    status: 'published',
    format: 'online',
    eventType: 'webinar',
    organizerId: 'org_tradingnew',
    organizerType: 'tradingnew',
    verificationStatus: 'verified',
    sourceType: 'tradingnew',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/Nicosia',
    language: ['EN'],
    country: null,
    city: null,
    venueName: null,
    venueAddress: null,
    capacity: null,
    registrationCount: 1240,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'beginner',
    topics: ['Macroeconomics', 'Investing basics'],
    learningOutcomes: [
      'Recognize the four phases of an economic cycle',
      'See how asset classes behaved in each phase since 1980',
      'Use the Economy section to locate the current regime',
    ],
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: agenda([
      ['18:00', 'Welcome and framing', 'Maria Petrou', 'Intro'],
      ['18:10', 'The four regimes, with data', 'Maria Petrou', 'Talk'],
      ['18:50', 'Live walkthrough: Economy section', 'Daniel Voss', 'Demo'],
      ['19:10', 'Q&A', 'All speakers', 'Discussion'],
    ]),
    speakers: speakers([
      ['MP', 'Maria Petrou', 'Head of Market Education', 'TradingNew'],
      ['DV', 'Daniel Voss', 'Macro analyst', 'TradingNew'],
    ]),
    isFeatured: true,
    inDays: 4,
    startHour: 18,
    durationHours: 1.5,
  },
  {
    ...BASE,
    id: 'evt_portfolio_workshop',
    slug: 'portfolio-construction-workshop-limassol',
    title: 'Portfolio Construction Workshop',
    shortDescription: 'Hands-on session: build a diversified allocation step by step.',
    description:
      'Three hours at a table with a spreadsheet and a real set of constraints. You leave with an allocation you wrote yourself and can defend.\n\nBring a laptop. No prior modelling experience needed.',
    coverGradient: 'linear-gradient(135deg,#0b2620,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'workshop',
    organizerId: 'org_keller',
    organizerType: 'individual',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Nicosia',
    language: ['EN'],
    country: 'Cyprus',
    city: 'Limassol',
    venueName: 'Columbia Plaza, Hall B',
    venueAddress: '223 Ayiou Andreou Street, Limassol 3036, Cyprus',
    latitude: 34.6742,
    longitude: 33.0444,
    capacity: 40,
    registrationCount: 22,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 45,
    currency: 'EUR',
    experienceLevel: 'intermediate',
    topics: ['Portfolio construction', 'Risk management'],
    learningOutcomes: [
      'Translate a goal and a horizon into an allocation range',
      'Size positions without over-concentrating',
      'Write down the rule you will rebalance by',
    ],
    intendedAudience:
      'Investors who already hold something and want a structure rather than a list of tips.',
    agenda: agenda([
      ['17:00', 'What an allocation is actually for', 'Anna Keller', 'Talk'],
      ['17:40', 'Exercise: your constraints on paper', null, 'Workshop'],
      ['18:30', 'Break', null, 'Break'],
      ['18:45', 'Building the model together', 'Anna Keller', 'Workshop'],
      ['19:40', 'Review and questions', 'Anna Keller', 'Discussion'],
    ]),
    speakers: speakers([['AK', 'Anna Keller', 'Financial adviser, CFA', 'Independent · CySEC-regulated']]),
    inDays: 6,
    startHour: 17,
    durationHours: 3,
  },
  {
    ...BASE,
    id: 'evt_limassol_meetup',
    slug: 'limassol-investors-meetup',
    title: 'Limassol Investors Meetup',
    shortDescription: 'Monthly community evening: markets talk, no sales pitches.',
    description:
      'A relaxed evening with other private investors. One short talk, then conversation.\n\nThe club has one rule and enforces it: nobody sells anything.',
    coverGradient: 'linear-gradient(135deg,#241a10,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'meetup',
    organizerId: 'org_cyprus_club',
    organizerType: 'community',
    verificationStatus: 'unverified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Nicosia',
    language: ['EN', 'RU'],
    country: 'Cyprus',
    city: 'Limassol',
    venueName: 'The Deck Café',
    venueAddress: 'Limassol Marina, 3601, Cyprus',
    latitude: 34.6503,
    longitude: 33.0333,
    capacity: 60,
    registrationCount: 34,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'all_levels',
    topics: ['Personal finance', 'Investing basics'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: agenda([
      ['19:00', 'Arrivals', null, 'Networking'],
      ['19:30', 'Short talk: what moved this month', 'Guest speaker', 'Talk'],
      ['20:00', 'Open conversation', null, 'Discussion'],
    ]),
    speakers: speakers([['CI', 'Cyprus Investors Club', 'Organizer & host', 'Community organizer']]),
    inDays: 10,
    startHour: 19,
    durationHours: 2.5,
  },
  {
    ...BASE,
    id: 'evt_cpi_live',
    slug: 'live-market-session-cpi-print',
    title: 'Live market session: reading the CPI print',
    shortDescription: 'Watch analysts interpret the inflation release in real time.',
    description:
      'The US CPI release, read live as it lands. Forty-five minutes, no slides — the number arrives and two analysts work through what it changes and what it does not.',
    coverGradient: 'linear-gradient(135deg,#1c1430,#081018)',
    status: 'published',
    format: 'online',
    eventType: 'live_market_session',
    organizerId: 'org_tradingnew',
    organizerType: 'tradingnew',
    verificationStatus: 'verified',
    sourceType: 'tradingnew',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'UTC',
    language: ['EN'],
    country: null,
    city: null,
    venueName: null,
    venueAddress: null,
    onlineMeetingUrl: 'https://live.tradingnew.space/rooms/cpi-session',
    capacity: null,
    registrationCount: 3900,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'advanced',
    topics: ['Macroeconomics'],
    learningOutcomes: [
      'Read a CPI release the way a desk reads it',
      'Separate the headline from what actually moved',
      'Know which follow-on data to wait for',
    ],
    intendedAudience: 'Investors comfortable with macro data who want to see it read in real time.',
    agenda: agenda([
      ['15:15', 'Pre-release setup: what is expected', 'Daniel Voss', 'Talk'],
      ['15:30', 'The print', null, 'Live'],
      ['15:40', 'Reaction across rates, FX and equities', 'Daniel Voss', 'Analysis'],
    ]),
    speakers: speakers([['DV', 'Daniel Voss', 'Macro analyst', 'TradingNew']]),
    inDays: 1,
    startHour: 15,
    durationHours: 0.75,
  },
  {
    ...BASE,
    id: 'evt_options_circle',
    slug: 'options-basics-study-group',
    title: 'Options basics study group',
    shortDescription: 'Weekly online circle working through options fundamentals.',
    description:
      'A study group, not a class. Twelve regulars work through one chapter a week and argue about it.\n\nNew members welcome at any point — the current run is on payoff diagrams.',
    coverGradient: 'linear-gradient(135deg,#0b2620,#081018)',
    status: 'published',
    format: 'online',
    eventType: 'meetup',
    organizerId: 'org_derivatives_circle',
    organizerType: 'community',
    verificationStatus: 'unverified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/Nicosia',
    language: ['EN'],
    country: null,
    city: null,
    venueName: null,
    venueAddress: null,
    capacity: 25,
    registrationCount: 12,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'beginner',
    topics: ['Options and derivatives'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: agenda([
      ['18:30', 'This week’s chapter', null, 'Discussion'],
      ['19:00', 'Worked examples', null, 'Workshop'],
    ]),
    speakers: speakers([['DS', 'Derivatives Study Circle', 'Organizer & host', 'Community organizer']]),
    inDays: 3,
    startHour: 18.5,
    durationHours: 1,
  },
  {
    ...BASE,
    id: 'evt_wealth_masterclass',
    slug: 'wealth-planning-masterclass',
    title: 'Wealth Planning Masterclass',
    shortDescription: 'Estate, tax and long-horizon planning for private investors.',
    description:
      'What to put in place before it matters: structure, succession and the tax questions people usually ask five years too late.',
    coverGradient: 'linear-gradient(135deg,#2a1220,#081018)',
    status: 'published',
    format: 'hybrid',
    eventType: 'masterclass',
    organizerId: 'org_lindqvist',
    organizerType: 'individual',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Nicosia',
    language: ['EN'],
    country: 'Cyprus',
    city: 'Limassol',
    venueName: 'Amathus Business Centre',
    venueAddress: '18 Spyrou Kyprianou, Limassol 4001, Cyprus',
    latitude: 34.7071,
    longitude: 33.0226,
    // Full, with the waitlist open — the state the design calls out.
    capacity: 30,
    registrationCount: 30,
    waitlistCount: 7,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 120,
    currency: 'EUR',
    experienceLevel: 'intermediate',
    topics: ['Wealth management', 'Regulation and taxation'],
    learningOutcomes: [
      'Map what you own against what happens to it',
      'Understand the common structures and what each costs',
      'Know which questions need a licensed adviser',
    ],
    intendedAudience: 'Private investors with assets across more than one country or asset class.',
    agenda: agenda([
      ['16:00', 'What planning is for', 'Sofia Lindqvist', 'Talk'],
      ['17:00', 'Structures and their trade-offs', 'Sofia Lindqvist', 'Talk'],
      ['18:00', 'Case discussion', null, 'Discussion'],
    ]),
    speakers: speakers([['SL', 'Sofia Lindqvist', 'Wealth planner', 'Independent']]),
    inDays: 24,
    startHour: 16,
    durationHours: 3,
  },
  {
    ...BASE,
    id: 'evt_london_macro',
    slug: 'london-macroeconomics-conference',
    title: 'The Rates Decade: London Macro Conference',
    shortDescription: 'A day on what higher-for-longer did to portfolios, and what comes next.',
    description:
      'Eight sessions across one day: policy, bonds, currencies and the long-run consequences of the last rate cycle.\n\nRun by the Thames Macro Institute, whose lectures are open to the public.',
    coverGradient: 'linear-gradient(135deg,#0a1c33,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'conference',
    organizerId: 'org_macro_institute',
    organizerType: 'institution',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/London',
    language: ['EN'],
    country: 'United Kingdom',
    city: 'London',
    venueName: 'Bishopsgate Institute',
    venueAddress: '230 Bishopsgate, London EC2M 4QH, United Kingdom',
    latitude: 51.5199,
    longitude: -0.0783,
    capacity: 300,
    registrationCount: 187,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 180,
    currency: 'GBP',
    experienceLevel: 'advanced',
    topics: ['Macroeconomics', 'Risk management'],
    learningOutcomes: [
      'Follow the transmission from policy rate to portfolio',
      'See where the consensus is currently wrong-footed',
      'Meet people who do this for a living',
    ],
    intendedAudience: 'Analysts, advisers and serious private investors.',
    agenda: agenda([
      ['09:00', 'Registration and coffee', null, 'Networking'],
      ['09:45', 'Opening: the decade in one chart', 'Prof. Alan Whitfield', 'Keynote'],
      ['11:00', 'Bonds after the repricing', 'Ruth Adeyemi', 'Panel'],
      ['14:00', 'Currencies and capital flows', 'Ruth Adeyemi', 'Talk'],
      ['16:30', 'Closing panel', 'All speakers', 'Panel'],
    ]),
    speakers: speakers([
      ['AW', 'Prof. Alan Whitfield', 'Director of Research', 'Thames Macro Institute'],
      ['RA', 'Ruth Adeyemi', 'Fixed income strategist', 'Thames Macro Institute'],
    ]),
    inDays: 38,
    startHour: 9,
    durationHours: 9,
  },
  {
    ...BASE,
    id: 'evt_berlin_fintech',
    slug: 'berlin-open-finance-workshop',
    title: 'Open Finance in Practice — Berlin Workshop',
    shortDescription: 'A working session on account access, data sharing and what it means for investors.',
    description:
      'Half a day with people building the plumbing: what open finance actually enables, what it does not, and where the regulation is heading.',
    coverGradient: 'linear-gradient(135deg,#0b2620,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'workshop',
    organizerId: 'org_berlin_fintech',
    organizerType: 'company',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/Berlin',
    language: ['EN', 'DE'],
    country: 'Germany',
    city: 'Berlin',
    venueName: 'Factory Berlin Mitte',
    venueAddress: 'Rheinsberger Str. 76/77, 10115 Berlin, Germany',
    latitude: 52.5352,
    longitude: 13.3927,
    capacity: 80,
    registrationCount: 41,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 60,
    currency: 'EUR',
    experienceLevel: 'intermediate',
    topics: ['Fintech', 'Regulation and taxation'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: 'Product people, analysts and investors following the sector.',
    agenda: agenda([
      ['10:00', 'What open finance changed', 'Lukas Brandt', 'Talk'],
      ['11:30', 'Hands-on: reading an account aggregation flow', null, 'Workshop'],
      ['14:00', 'Regulation panel', 'All speakers', 'Panel'],
    ]),
    speakers: speakers([
      ['LB', 'Lukas Brandt', 'Head of Platform', 'Berlin Fintech Collective'],
      ['NK', 'Nadia Køhler', 'Regulatory counsel', 'Independent'],
    ]),
    inDays: 17,
    startHour: 10,
    durationHours: 5,
  },
  {
    ...BASE,
    id: 'evt_ta_masterclass',
    slug: 'technical-analysis-masterclass-online',
    title: 'Technical Analysis Masterclass',
    shortDescription: 'Four hours online: structure, levels and what indicators can and cannot tell you.',
    description:
      'A full session on reading a chart properly — and on the limits of doing so. Includes an honest hour on what technical analysis does not do.',
    coverGradient: 'linear-gradient(135deg,#1c1430,#081018)',
    status: 'published',
    format: 'online',
    eventType: 'masterclass',
    organizerId: 'org_keller',
    organizerType: 'individual',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/Nicosia',
    language: ['EN'],
    country: null,
    city: null,
    venueName: null,
    venueAddress: null,
    onlineMeetingUrl: 'https://meet.example/ta-masterclass',
    capacity: 120,
    registrationCount: 74,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 35,
    currency: 'EUR',
    experienceLevel: 'intermediate',
    topics: ['Technical analysis', 'Trading'],
    learningOutcomes: [
      'Read market structure before reaching for an indicator',
      'Use two indicators well rather than six badly',
      'Recognise where the method stops being informative',
    ],
    intendedAudience: 'Investors who already look at charts and want to do it deliberately.',
    agenda: agenda([
      ['14:00', 'Structure first', 'Anna Keller', 'Talk'],
      ['15:30', 'Indicators, honestly', 'Anna Keller', 'Talk'],
      ['17:00', 'Live chart review', null, 'Workshop'],
    ]),
    speakers: speakers([['AK', 'Anna Keller', 'Financial adviser, CFA', 'Independent']]),
    inDays: 13,
    startHour: 14,
    durationHours: 4,
  },
  {
    ...BASE,
    id: 'evt_tokyo_etf',
    slug: 'tokyo-etf-seminar',
    title: 'ETF Investing Seminar — Tokyo',
    shortDescription: 'Index construction, currency hedging and the Japanese ETF market.',
    description:
      'An evening seminar on how index funds are actually built, and what currency hedging costs a yen-based investor.',
    coverGradient: 'linear-gradient(135deg,#2a1220,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'conference',
    organizerId: 'org_tokyo_etf',
    organizerType: 'institution',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Tokyo',
    language: ['JA', 'EN'],
    country: 'Japan',
    city: 'Tokyo',
    venueName: 'Marunouchi Conference Square',
    venueAddress: '2-5-1 Marunouchi, Chiyoda City, Tokyo 100-0005, Japan',
    latitude: 35.6812,
    longitude: 139.7649,
    capacity: 150,
    registrationCount: 96,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'all_levels',
    topics: ['ETFs', 'Investing basics'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: agenda([
      ['18:30', 'How an index is built', 'Haruka Ishii', 'Talk'],
      ['19:30', 'Hedged or unhedged', 'Kenji Morita', 'Talk'],
    ]),
    speakers: speakers([
      ['HI', 'Haruka Ishii', 'Index research', 'Tokyo ETF Forum'],
      ['KM', 'Kenji Morita', 'Portfolio manager', 'Independent'],
    ]),
    inDays: 21,
    startHour: 18.5,
    durationHours: 2,
  },
  {
    ...BASE,
    id: 'evt_mumbai_finance',
    slug: 'mumbai-personal-finance-meetup',
    title: 'Mumbai Personal Finance Meetup',
    shortDescription: 'Salaried professionals comparing notes on saving, tax and first investments.',
    description:
      'A monthly evening for people who earn a salary and want to do something sensible with it. Practical, local and specific.',
    coverGradient: 'linear-gradient(135deg,#241a10,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'meetup',
    organizerId: 'org_mumbai_money',
    organizerType: 'community',
    verificationStatus: 'unverified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Kolkata',
    language: ['EN'],
    country: 'India',
    city: 'Mumbai',
    venueName: 'Bandra Community Hall',
    venueAddress: 'Hill Road, Bandra West, Mumbai 400050, India',
    latitude: 19.0596,
    longitude: 72.8295,
    capacity: 50,
    registrationCount: 28,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'beginner',
    topics: ['Personal finance', 'Investing basics'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: agenda([
      ['18:00', 'Arrivals', null, 'Networking'],
      ['18:30', 'Topic of the month', null, 'Talk'],
      ['19:15', 'Open questions', null, 'Discussion'],
    ]),
    speakers: speakers([['MM', 'Mumbai Money Circle', 'Organizer & host', 'Community organizer']]),
    inDays: 9,
    startHour: 18,
    durationHours: 2,
  },
  {
    ...BASE,
    id: 'evt_ny_risk',
    slug: 'new-york-portfolio-risk-session',
    title: 'Portfolio Risk Working Session — New York',
    shortDescription: 'A closed-room session on concentration, correlation and what breaks in a drawdown.',
    description:
      'Small-group session with risk consultants. Bring a portfolio you actually hold; leave with a list of what you had not measured.',
    coverGradient: 'linear-gradient(135deg,#1c1430,#081018)',
    status: 'published',
    format: 'hybrid',
    eventType: 'workshop',
    organizerId: 'org_hudson_risk',
    organizerType: 'company',
    verificationStatus: 'verified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'America/New_York',
    language: ['EN'],
    country: 'United States',
    city: 'New York',
    venueName: 'The Yard, Flatiron',
    venueAddress: '110 W 40th St, New York, NY 10018, United States',
    latitude: 40.7536,
    longitude: -73.9847,
    capacity: 24,
    registrationCount: 19,
    waitlistCount: 0,
    waitlistEnabled: true,
    priceType: 'paid',
    priceAmount: 220,
    currency: 'USD',
    experienceLevel: 'advanced',
    topics: ['Risk management', 'Portfolio construction'],
    learningOutcomes: [
      'Measure concentration properly, not by feel',
      'See where correlations go in a real drawdown',
      'Leave with a monitoring checklist',
    ],
    intendedAudience: 'Advisers, family offices and investors managing meaningful capital.',
    agenda: agenda([
      ['13:00', 'What risk measures miss', 'Gregory Nunes', 'Talk'],
      ['14:00', 'Working session on live portfolios', null, 'Workshop'],
      ['16:00', 'Building your checklist', 'Gregory Nunes', 'Workshop'],
    ]),
    speakers: speakers([['GN', 'Gregory Nunes', 'Partner', 'Hudson Risk Partners']]),
    inDays: 31,
    startHour: 13,
    durationHours: 4,
  },
  {
    ...BASE,
    id: 'evt_cyprus_fintech_summit',
    slug: 'cyprus-fintech-summit',
    title: 'Cyprus Fintech Summit',
    shortDescription: 'Two-day conference: payments, digital assets and regulation.',
    description:
      'An industry conference run outside TradingNew. Registration, payment and attendance are handled entirely by the organizer.',
    coverGradient: 'linear-gradient(135deg,#0a1c33,#081018)',
    status: 'published',
    format: 'hybrid',
    eventType: 'conference',
    organizerId: 'org_cfs_events',
    organizerType: 'company',
    verificationStatus: 'unverified',
    sourceType: 'external',
    externalUrl: 'https://cyprusfintechsummit.example/2026',
    externalDomain: 'cyprusfintechsummit.example',
    externalTrusted: true,
    timezone: 'Asia/Nicosia',
    language: ['EN'],
    country: 'Cyprus',
    city: 'Nicosia',
    venueName: 'Filoxenia Conference Centre',
    venueAddress: '1 Kyriakou Matsi, Nicosia 1082, Cyprus',
    latitude: 35.1745,
    longitude: 33.3642,
    capacity: null,
    registrationCount: 0,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'external',
    priceAmount: 180,
    currency: 'EUR',
    experienceLevel: 'all_levels',
    topics: ['Fintech', 'Regulation and taxation', 'Crypto and digital assets'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: [],
    speakers: speakers([['CF', 'CFS Events Ltd', 'Organizer', 'Conference organizer']]),
    inDays: 48,
    startHour: 9,
    durationHours: 9,
  },
  {
    ...BASE,
    id: 'evt_athens_etf_external',
    slug: 'etf-investing-conference-athens',
    title: 'ETF Investing Conference Athens',
    shortDescription: 'Index investing, factor strategies and the European ETF market.',
    description:
      'Run by an organizer TradingNew has not verified. Registration happens on their website.',
    coverGradient: 'linear-gradient(135deg,#0b2620,#081018)',
    status: 'published',
    format: 'in_person',
    eventType: 'conference',
    organizerId: 'org_cfs_events',
    organizerType: 'company',
    verificationStatus: 'unverified',
    sourceType: 'external',
    externalUrl: 'https://etfcon-europe.example/athens',
    externalDomain: 'etfcon-europe.example',
    // Deliberately untrusted, so the "leaving TradingNew" confirmation has a case.
    externalTrusted: false,
    timezone: 'Europe/Athens',
    language: ['EN', 'EL'],
    country: 'Greece',
    city: 'Athens',
    venueName: 'Megaron Athens Concert Hall',
    venueAddress: 'Vasilissis Sofias & Kokkali, Athens 115 21, Greece',
    latitude: 37.9793,
    longitude: 23.7527,
    capacity: null,
    registrationCount: 0,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'external',
    priceAmount: 95,
    currency: 'EUR',
    experienceLevel: 'all_levels',
    topics: ['ETFs', 'Investing basics'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: [],
    speakers: speakers([['EE', 'ETFcon Europe', 'Organizer', 'Conference organizer']]),
    inDays: 60,
    startHour: 10,
    durationHours: 7,
  },
  {
    ...BASE,
    id: 'evt_cancelled_signals',
    slug: 'algorithmic-signals-evening-cancelled',
    title: 'Algorithmic Signals Evening',
    shortDescription: 'This event was cancelled by the organizer.',
    description: 'The organizer cancelled this event. Everyone registered has been notified.',
    coverGradient: 'linear-gradient(135deg,#141b24,#081018)',
    status: 'cancelled',
    cancellationReason: 'The speaker withdrew and no replacement could be arranged in time.',
    format: 'online',
    eventType: 'webinar',
    organizerId: 'org_derivatives_circle',
    organizerType: 'community',
    verificationStatus: 'unverified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Europe/Nicosia',
    language: ['EN'],
    country: null,
    city: null,
    venueName: null,
    venueAddress: null,
    capacity: 100,
    registrationCount: 63,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'intermediate',
    topics: ['Trading', 'Technical analysis'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: [],
    speakers: speakers([['DS', 'Derivatives Study Circle', 'Organizer', 'Community organizer']]),
    inDays: 15,
    startHour: 19,
    durationHours: 1.5,
  },
  {
    ...BASE,
    id: 'evt_completed_crypto_tax',
    slug: 'crypto-tax-basics-completed',
    title: 'Crypto tax basics',
    shortDescription: 'What a disposal is, and when one happened without you noticing.',
    description:
      'A past session on the tax treatment of digital assets. The recording is with the organizer.',
    coverGradient: 'linear-gradient(135deg,#0b2620,#081018)',
    status: 'completed',
    format: 'online',
    eventType: 'webinar',
    organizerId: 'org_cyprus_club',
    organizerType: 'community',
    verificationStatus: 'unverified',
    sourceType: 'community',
    externalUrl: null,
    externalDomain: null,
    externalTrusted: false,
    timezone: 'Asia/Nicosia',
    language: ['EN'],
    country: 'Cyprus',
    city: 'Limassol',
    venueName: null,
    venueAddress: null,
    capacity: 60,
    registrationCount: 52,
    waitlistCount: 0,
    waitlistEnabled: false,
    priceType: 'free',
    priceAmount: null,
    currency: null,
    experienceLevel: 'beginner',
    topics: ['Crypto and digital assets', 'Regulation and taxation'],
    learningOutcomes: DEFAULT_OUTCOMES,
    intendedAudience: DEFAULT_AUDIENCE,
    agenda: [],
    speakers: speakers([['CI', 'Cyprus Investors Club', 'Organizer', 'Community organizer']]),
    inDays: -18,
    startHour: 18,
    durationHours: 1.5,
  },
];

/**
 * Materialises the catalogue against a supplied clock. The caller owns "now" so
 * a page, a test and a verification script can all agree on what is upcoming.
 */
/**
 * The instant at which the wall clock in `timeZone` reads `hour` on that day.
 *
 * Needed because `startHour` in the fixtures is the local time an organizer would
 * write on a poster — "18:00" for an evening webinar in Nicosia. Treating it as
 * UTC made every event three hours late in summer, which is the kind of error
 * that looks like a formatting choice rather than a wrong number.
 *
 * Approximate at the exact moment of a DST transition, which no fixture uses.
 */
function localInstant(dayMs: number, hour: number, timeZone: string): Date {
  const guess = new Date(dayMs + hour * HOUR);
  const inZone = new Date(guess.toLocaleString('en-US', { timeZone }));
  const inUtc = new Date(guess.toLocaleString('en-US', { timeZone: 'UTC' }));

  return new Date(guess.getTime() - (inZone.getTime() - inUtc.getTime()));
}

export function seedEvents(now: Date): TradingEvent[] {
  const midnight = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());

  return SEEDS.map((seed) => {
    const { inDays, startHour, durationHours, ...event } = seed;
    const start = localInstant(midnight + inDays * DAY, startHour, event.timezone);
    const end = new Date(start.getTime() + durationHours * HOUR);
    const created = new Date(start.getTime() - 30 * DAY);

    return {
      ...event,
      startsAt: start.toISOString(),
      endsAt: end.toISOString(),
      createdAt: created.toISOString(),
      updatedAt: created.toISOString(),
      publishedAt: event.status === 'draft' ? null : created.toISOString(),
    } satisfies TradingEvent;
  });
}

export function seedOrganizer(id: string): Organizer | null {
  return SEED_ORGANIZERS.find((organizer) => organizer.id === id) ?? null;
}

export function seedOrganizerBySlug(slug: string): Organizer | null {
  return SEED_ORGANIZERS.find((organizer) => organizer.slug === slug) ?? null;
}
