/**
 * The code-execution container, carried through one answer.
 *
 * The failure this exists to end, from production logs:
 *
 *   400 invalid_request_error — container_id is required when there are pending
 *   tool uses generated by code execution with tools
 *
 * The web-search tool this loop offers runs its dynamic filtering inside a
 * code-execution container, so a response that searched can come back owning
 * one. Continuing that conversation means telling the API which container the
 * pending work belongs to; without it the next request in the loop is rejected,
 * and the rejection is marked non-retryable because retrying the same body
 * would fail identically. What a person saw was the generic "I could not finish
 * that one" — the honest failure answer, for a request the API had told us
 * exactly how to fix.
 *
 * Two shapes, and they are not the same shape: a response returns
 * `container: { id, expires_at } | null`, and a request takes
 * `container?: string` — the identifier, not the object. That asymmetry is the
 * whole of this module.
 *
 * **Request-local by construction.** This holds no state; the caller keeps the
 * identifier in a local inside one `askVoyager` execution, so it cannot reach a
 * database, a browser, or another person's question. Nothing here writes
 * anywhere.
 *
 * Import-free, so the unit harness compiles it alone.
 */

/** The container field as a response carries it. */
export type ResponseContainer = { id?: unknown } | null | undefined;

/**
 * The container to send with the next request in this answer.
 *
 * Keeps what it has when a response mentions no container — a round that did
 * not touch code execution does not mean the container is gone, and dropping it
 * would reproduce the 400 on the round after. Adopts a new identifier when one
 * arrives, because the API is the only thing entitled to name one.
 *
 * Never invents one: a value that is not a non-empty string leaves the current
 * one alone.
 */
export function nextContainer(
  current: string | undefined,
  container: ResponseContainer
): string | undefined {
  const id = container?.id;
  if (typeof id === 'string' && id.trim()) return id;
  return current;
}

/**
 * The `container` field for a request, or nothing.
 *
 * Spread into the request body, so a conversation that never used code
 * execution sends exactly what it sent before this existed.
 */
export function containerParam(current: string | undefined): { container?: string } {
  return current ? { container: current } : {};
}
